---
apiVersion: v1
kind: Service
metadata:
  name: be-chatbot-flow-alexa-service-qa
  labels:
    app: be-chatbot-flow-alexa-service-qa
spec:
  type: NodePort
  ports:
    - port: 8453
      protocol: TCP
      targetPort: 8453
      nodePort: 30013
  selector:
    app: be-chatbot-flow-alexa-service-qa
    tier: compute
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: be-chatbot-flow-alexa-service-qa
  labels:
    app: be-chatbot-flow-alexa-service-qa
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: be-chatbot-flow-alexa-service-qa
        tier: compute
    spec:
      containers:
        - image: index.docker.io/dinersclub/be_chatbot_flow_alexa_repo_qa:latest
          imagePullPolicy: Always
          name: be-chatbot-flow-alexa-service-qa
          env:
          ports:
            - containerPort: 8453
              name: web
      imagePullSecrets:
        - name: myregistrykey
