# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
logging:
    level:
        ROOT: INFO
        ec.com.dinersclub.chatbot: INFO

spring:
    application:
        name: flowDataUpdateBackend
    jackson:
        serialization.write_dates_as_timestamps: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://sl-us-south-1-portal.1.dblayer.com:44736/flow_backend
        username: admin
        password: XGXFKWFILYDWGPWW
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      database: POSTGRESQL
      show-sql: true
      properties:
              hibernate.id.new_generator_mappings: true
              hibernate.cache.use_second_level_cache: false
              hibernate.cache.use_query_cache: false
              hibernate.generate_statistics: true
              hibernate.ddl-auto: update
              hibernate.generate-ddl: true
              hibernate.temp:
                   use_jdbc_metadata_defaults: false
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

server:
  port: 8282
  servlet:
    context-path: /alexa-demo

# =============================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# =============================================================================
application:
  backend-url: http://10.76.196.169:30080/chatbot-admin-backend/api/
  proxy-enabled: false
  proxy-address: 192.168.18.35
  proxy_port: 9090
  watson_workspace: d1a19813-b2cd-4ce3-a66b-1e64c4b2557a
  watson_api_key: UPAaIIWh51-m7gaoaZpcYFHAXkDJa2MR8792K1LZq3P7
  watson_version: 2018-06-06